[build]
target = "riscv32imafc-esp-espidf"

[target.riscv32imafc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32p4"
ESP_IDF_VERSION = "v5.5.2"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "/Users/joelbell/teleios/display-firmware/firmware/sdkconfig.defaults", relative = false }
